# Generated by Django 4.2.2 on 2023-06-21 08:32

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0003_alter_files_options_alter_images_options_files_tab_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='element',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='tab', chained_model_field='tab', on_delete=django.db.models.deletion.CASCADE, related_name='files', show_all='False', to='elements.element', verbose_name='Элемент'),
        ),
        migrations.AlterField(
            model_name='images',
            name='element',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='tab', chained_model_field='tab', on_delete=django.db.models.deletion.CASCADE, related_name='images', show_all='False', to='elements.element', verbose_name='Элемент'),
        ),
    ]
