# Generated by Django 4.2.2 on 2023-06-22 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0004_alter_files_element_alter_images_element'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files',
            options={'ordering': ['tab', 'element'], 'verbose_name': 'Файлы элемента', 'verbose_name_plural': '2.1 Файлы элементов'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ['tab', 'element'], 'verbose_name': 'Изображения элемента', 'verbose_name_plural': '2.2 Изображения элементов'},
        ),
        migrations.AddField(
            model_name='element',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='files',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='elements.element', verbose_name='Элемент'),
        ),
        migrations.AlterField(
            model_name='files',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='images',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='elements.element', verbose_name='Элемент'),
        ),
        migrations.AlterField(
            model_name='images',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
